import os
import subprocess

# Define the base command and parameters
base_command = [
    "python", "-W", "ignore", "run_vila.py",
    "--model-path", "Efficient-Large-Model/VILA1.5-3b",
    "--conv-mode", "vicuna_v1"
]

# Define the 5 different queries
queries = [
    "<video>\n What is happening in the video?",
    "<video>\n Describe the traffic conditions in the video.",
    "<video>\n Are there any potential hazards in the video?",
    "<video>\n What actions are being performed by the objects in the video?",
    "<video>\n What unusual events occur in the video?"
]

# Base directory for videos and output
video_dir = "/home/mi3/Downloads/COOOL_Benchmark_Driving_Scenes"
output_dir = "/home/mi3/Downloads/bboxTest/vila_output"

# Ensure the output directory exists
os.makedirs(output_dir, exist_ok=True)

# Iterate over all 200 videos
for video_id in range(1, 201):
    video_filename = f"video_{video_id:04d}.mp4"
    video_path = os.path.join(video_dir, video_filename)

    if not os.path.exists(video_path):
        print(f"Video file {video_path} does not exist. Skipping.")
        continue

    # Set the output file name
    output_file = os.path.join(output_dir, f"vila_description_{video_filename.replace('.mp4', '.txt')}")

    # Run the command for each query and save the output
    with open(output_file, "w") as f:
        for i, query in enumerate(queries):
            print(f"Running query {i + 1} for video {video_filename}: {query}")
            command = base_command + ["--video-file", video_path, "--query", query]
            try:
                # Run the command and capture the output
                result = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)

                # Extract meaningful output by finding the last non-empty line
                result_lines = result.stdout.splitlines()
                meaningful_output = next((line for line in reversed(result_lines) if line.strip()), None)

                # Write query and output to the file
                f.write(f"\nQuery {i + 1}: {query}\n")
                if meaningful_output:
                    f.write(meaningful_output + "\n")
                else:
                    f.write("No result generated by the model.\n")
                f.write("\n" + "=" * 80 + "\n")

                # Print success message
                print(f"Query {i + 1} for video {video_filename} completed successfully.")
            except Exception as e:
                # Write any errors to the file
                f.write(f"\nQuery {i + 1}: {query}\n")
                f.write(f"Error: {str(e)}\n")
                f.write("\n" + "=" * 80 + "\n")
                print(f"Error running query {i + 1} for video {video_filename}: {e}")

    print(f"Output for {video_filename} saved to {output_file}.")

print("All videos processed.")
